In [3]:
# Dependencies
import requests
import json
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests

# REFERENCE LINK FOR COLUMN DEFINITION
# https://www.fema.gov/openfema-dataset-individual-assistance-housing-registrants-large-disasters-v1

# FEMA Data | KINGWOOD Repair Amount > 25000 | 422 rows
url = "https://www.fema.gov/api/open/v1/IndividualAssistanceHousingRegistrantsLargeDisasters?$filter=damagedStateAbbreviation%20eq%20%27TX%27%20and%20damagedCity%20eq%20%27THE WOODLANDS%27%20and%20repairAmount%20gt%2025000"

# Request articles
articles = requests.get(url).json()

print("FEMA DataSet : Individual Assistance Housing Registrants Large Disasters | WOODLANDS | Repair Amount > 25000")

data_df = pd.DataFrame(articles["IndividualAssistanceHousingRegistrantsLargeDisasters"])
data_df

FEMA DataSet : Individual Assistance Housing Registrants Large Disasters | WOODLANDS | Repair Amount > 25000

,censusBlockId,censusYear,damagedCity,damagedStateAbbreviation,damagedZipCode,destroyed,disasterNumber,floodDamage,floodInsurance,foundationDamage,...,replacementAssistanceEligible,residenceType,roofDamage,roofDamageAmount,rpfvl,sbaEligible,specialNeeds,tsaCheckedIn,tsaEligible,waterLevel
0,483396914002010,2017,THE WOODLANDS,TX,77380,False,4332,True,False,False,...,False,House/Duplex,False,None,29414.61,False,False,True,True,12
1,483396914002015,2017,THE WOODLANDS,TX,77380,False,4332,True,False,False,...,False,House/Duplex,False,None,30069.78,False,False,False,True,16
2,483396913021008,2017,THE WOODLANDS,TX,77381,False,4332,True,False,False,...,False,House/Duplex,False,None,33407.06,False,False,False,True,62

In [4]:
export_csv = data_df.to_csv ("IAHRLD_4332_harvey_WOODLANDS_25000.csv", encoding='utf-8', index=False, header=True)